service: compress-tool

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: prod
  region: eu-west-1
  tags:
    proyecto: ${self:service}
  httpApi:
    useProviderTags: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:*'
          Resource: 'arn:aws:s3:::[[YOUR S3 BUCKET]]/*'


functions:
  uploadfilecompress:
    handler: lambda/uploadfilecompress/index.handler
    memorySize: 128
    timeout: 10
    events:
      - httpApi:
          path: /uploadfilecompress
          method: post
  compressfiles:
    handler: lambda/compressfiles/index.handler
    memorySize: 2048
    timeout: 15
    events:
      - httpApi:
          path: /compressfiles
          method: post
    layers:
      - [[ARN FOR "ZIP" NODEJS PACKAGE]]