service: storage-tool

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: prod
  region: eu-west-1
  tags:
    project: ${self:service}
  httpApi:
    useProviderTags: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'cloudfront:CreateInvalidation'
          Resource: '*'
        - Effect: Allow
          Action:
            - 's3:*'
          Resource: 'arn:aws:s3:::[[YOUR S3 BUCKET]]/*'


functions:
  uploadfile:
    handler: lambda/uploadfile/index.handler
    memorySize: 128
    timeout: 10
    events:
      - httpApi:
          path: /uploadfile
          method: post
  deletefile:
    handler: lambda/deletefile/index.handler
    memorySize: 128
    timeout: 10
    events:
      - httpApi:
          path: /deletefile
          method: post
